extends:
  - "@commitlint/config-conventional"

rules:
  body-max-line-length:
    - 0
    - always
    - Infinity
  type-enum:
    - 2
    - always
    - [build, ci, docs, feat, fix, perf, refactor, test]
  scope-enum:
    - 2
    - always
    - [
        repo,
        openfang-types,
        openfang-memory,
        openfang-runtime,
        openfang-wire,
        openfang-api,
        openfang-kernel,
        openfang-cli,
        openfang-channels,
        openfang-migrate,
        openfang-skills,
        openfang-desktop,
        openfang-hands,
        openfang-extensions,
        xtask,
        ci,
        docs,
      ]
  subject-case:
    - 0
    - always
    - []
